Repository nnyyxxxx/dwm, pull requests merged in 2024-09, with the labels that each got.

#3 cd function broken again.
  extra/.bashrc
Labels: bug

#7 feat: implement uninstall script
  Readme.md
  uninstall.sh
Labels: documentation, enhancement

#8 feat: add pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#9 docs: add commit messages / pr titles guidelines
  .github/contributing.md
Labels: documentation, enhancement

#10 docs: remove a rule
  .github/contributing.md
Labels: documentation, enhancement

#11 refact(sh): better error handling + build deps for paru
  install.sh
Labels: enhancement

#12 refact(sh): use symlinks instead of hard-copying files
  install.sh
  uninstall.sh
Labels: enhancement

#13 fix(sh): create `/usr/share/icons/default/index.theme` before editing it
  install.sh
Labels: bug

#14 fix: fix issues with scripts
  install.sh
  suckless/dmenu/dmenu
  suckless/dmenu/dmenu.o
  suckless/dmenu/drw.o
  suckless/dmenu/stest
  suckless/dmenu/stest.o
  suckless/dmenu/util.o
  suckless/dwm/dwm
  suckless/dwm/dwm.o
  suckless/st/st
  suckless/st/st.o
  suckless/st/x.o
Labels: bug

#16 fix: redirect output to /dev/null
  uninstall.sh
Labels: bug

#17 docs: implement uninstall section
  Readme.md
Labels: enhancement

#18 refact: Remove options from template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#19 docs: add on to the dwm sections
  Readme.md
Labels: documentation, enhancement

#21 refact: use users actual username and hostname
  extra/fastfetch/config.jsonc
Labels: enhancement

#22 chore: update license
  LICENSE
Labels: enhancement

#23 fix: make makepkg non-user-interactive
  install.sh
Labels: bug

#25 fix: make backups in .config instead of the users home dir
  install.sh
  uninstall.sh
Labels: bug

#26 chore: re-order functions
  uninstall.sh
Labels: enhancement

#27 docs: update uninstalling section
  Readme.md
Labels: documentation

#28 docs: update previews
  .github/images/previewScript.png
  .github/images/previewScript2.png
  Readme.md
Labels: documentation

#29 docs: add a new note
  Readme.md
Labels: documentation

#31 fix: fix history saving
  extra/.zshrc
Labels: bug

#32 fix: fix history saving 2
  extra/.zshrc
Labels: bug

#34 fix: path not properly set
  extra/.zshrc
Labels: bug

#35 revert: revert auto-completion
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/.circleci/config.yml
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/.editorconfig
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/.rspec
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/.rubocop.yml
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/.ruby-version
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/CHANGELOG.md
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/DESCRIPTION
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/Dockerfile
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/Gemfile
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/Gemfile.lock
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/INSTALL.md
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/LICENSE
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/Makefile
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/README.md
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/URL
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/VERSION
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/ZSH_VERSIONS
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/install_test_zsh.sh
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/async_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/integrations/auto_cd_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/integrations/bracketed_paste_magic_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/integrations/client_zpty_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/integrations/glob_subst_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/integrations/rebound_bracket_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/integrations/vi_mode_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/integrations/wrapped_widget_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/integrations/zle_input_stack_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/kill_ring_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/line_init_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/multi_line_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/options/buffer_max_size_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/options/highlight_style_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/options/original_widget_prefix_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/options/strategy_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/options/widget_lists_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/spec_helper.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/strategies/completion_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/strategies/history_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/strategies/match_prev_cmd_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/strategies/special_characters_helper.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/terminal_session.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/widgets/disable_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/widgets/enable_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/widgets/fetch_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/spec/widgets/toggle_spec.rb
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/src/async.zsh
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/src/bind.zsh
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/src/config.zsh
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/src/fetch.zsh
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/src/highlight.zsh
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/src/start.zsh
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/src/strategies/completion.zsh
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/src/strategies/history.zsh
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/src/strategies/match_prev_cmd.zsh
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/src/util.zsh
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/src/widgets.zsh
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
  extra/.zshplugins/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
  extra/.zshrc
Labels: wontfix

#38 refact: remove save-floats and replace with alternative
  suckless/dwm/dwm
  suckless/dwm/dwm.c
  suckless/dwm/dwm.o
  suckless/dwm/patches/dwm-savefloats-20181212-b69c870.diff
Labels: enhancement

#39 fix: fix windows not spawning in center
  suckless/dwm/dwm
  suckless/dwm/dwm.c
  suckless/dwm/dwm.o
Labels: bug

#40 fix: fix window moving in tiled mode
  suckless/dwm/dwm
  suckless/dwm/dwm.c
  suckless/dwm/dwm.o
  suckless/dwm/patches/dwm-tiledmove-20231210-b731.diff
Labels: bug

#42 refact: change color scheming
  .github/images/preview.png
  Readme.md
  extra/.xinitrc
  extra/.zshrc
  extra/catppuccin-wallpapers/README.md
  extra/catppuccin-wallpapers/mocha-wall/alpine-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/android-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/apple-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/apple-colors-big-4k.png
  extra/catppuccin-wallpapers/mocha-wall/arch-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/arco-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/artix-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/buttons.png
  extra/catppuccin-wallpapers/mocha-wall/cat-sound.png
  extra/catppuccin-wallpapers/mocha-wall/cat_bunnies.png
  extra/catppuccin-wallpapers/mocha-wall/cat_colors.png
  extra/catppuccin-wallpapers/mocha-wall/cat_pacman.png
  extra/catppuccin-wallpapers/mocha-wall/centos-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/debian-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/deepin-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/elementary-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/endeavour-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/fedora-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/freebsd-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/garuda-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/gentoo-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/hashtags-black.png
  extra/catppuccin-wallpapers/mocha-wall/heart.jpg
  extra/catppuccin-wallpapers/mocha-wall/hearts.png
  extra/catppuccin-wallpapers/mocha-wall/manjaro-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/mint-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/mxlinux-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/nix-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/opensuse-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/pop-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/rainbow.png
  extra/catppuccin-wallpapers/mocha-wall/raspberry-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/solus-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/tetris.png
  extra/catppuccin-wallpapers/mocha-wall/tux-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/virus.png
  extra/catppuccin-wallpapers/mocha-wall/void-black-4k.png
  extra/catppuccin-wallpapers/mocha-wall/windows-black.png
  extra/catppuccin-wallpapers/mocha-wall/windows-error.jpg
  extra/fastfetch/config.jsonc
  extra/picom/picom.conf
  install.sh
  suckless/dmenu/config.def.h
  suckless/dmenu/config.h
  suckless/dmenu/dmenu
  suckless/dmenu/dmenu.o
  suckless/dwm/config.def.h
  suckless/dwm/config.h
  suckless/dwm/dwm
  suckless/dwm/dwm.o
Labels: enhancement

#43 fix: remove extra picom
  install.sh
Labels: bug

#44 feat: implement gitignore
  .github/images/preview.png
  .gitignore
  extra/fastfetch/config.jsonc
Labels: enhancement

#45 refact: disable opacity in fullscreen
  extra/picom/picom.conf
Labels: enhancement

#46 fix: fix feh not properly setting the wallpaper
  extra/.xinitrc
Labels: bug

#48 refact: remove window snapping in floating
  suckless/dwm/dwm.c
Labels: enhancement

#50 feat: add extra prints
  Readme.md
  extra/.zshrc
  suckless/dwm/dwm
  suckless/dwm/dwm.o
  update.sh
Labels: enhancement

#51 feat: add extra preview
  .github/images/previewScript3.png
  Readme.md
Labels: enhancement

#52 docs: update logo
  .github/images/logo.png
  Readme.md
Labels: documentation

#53 feat: remove opacity for dmenu
  extra/picom/picom.conf
Labels: enhancement

#54 feat: implement new keybinds
  Readme.md
  suckless/dwm/config.def.h
  suckless/dwm/config.h
  suckless/dwm/dwm
  suckless/dwm/dwm.o
Labels: enhancement

#55 refact: optimize make files
  Readme.md
  suckless/dmenu/Makefile
  suckless/dmenu/README
  suckless/dmenu/config.def.h
  suckless/dmenu/config.mk
  suckless/dmenu/dmenu
  suckless/dmenu/dmenu.o
  suckless/dmenu/stest
  suckless/dwm/Makefile
  suckless/dwm/README
  suckless/dwm/config.def.h
  suckless/dwm/config.h
  suckless/dwm/config.mk
  suckless/dwm/drw.o
  suckless/dwm/dwm
  suckless/dwm/dwm.o
  suckless/dwm/dwm.png
  suckless/dwm/util.o
  suckless/st/FAQ
  suckless/st/LEGACY
  suckless/st/Makefile
  suckless/st/README
  suckless/st/TODO
  suckless/st/config.def.h
Labels: enhancement

#56 refact: replace vlc with mpv
  extra/.zshrc
  install.sh
  uninstall.sh
  update.sh
Labels: enhancement

#57 refact: fix missnamed print
  uninstall.sh
Labels: bug, enhancement

#58 refact: make ffmpeg save videos to a specific dir
  extra/.zshrc
Labels: enhancement

#59 refact: make history not show a predefined amount
  extra/.zshrc
Labels: enhancement

#60 Blocks
  extra/.xinitrc
  suckless/dwm/config.h
  suckless/dwm/dwm.c
  suckless/dwm/patches/dwm-statuscolors-20220322-bece862.diff
  suckless/dwmblocks/LICENSE
  suckless/dwmblocks/Makefile
  suckless/dwmblocks/config.h
  suckless/dwmblocks/dwmblocks
  suckless/dwmblocks/dwmblocks.c
Labels: enhancement

#61 refact: add blocks to scripts
  Readme.md
  extra/debloat.sh
  install.sh
  uninstall.sh
  update.sh
Labels: enhancement
